### ISSUE TITLE
понравился результат, но не получилось посмотреть

### ISSUE THREAD

**Issue by VVE** [oozywaters/Halcyon#1]
Здравствуйте! Пытался посмотреть клон,  при запуске 
npm i
у меня возникли ошибки:
![default](https://cloud.githubusercontent.com/assets/1208669/6725076/8b5bb8c4-ce14-11e4-982b-67037e0bde19.png)
, и при последующем запуске сервера 
.\node_modules.bin\enb server
на страницу выводятся ошибки:
Error: Cannot find module 'postcss'
   at Function.Module._resolveFilename (module.js:336:15)
   at Function.Module._load (module.js:278:25)
   at Module.require (module.js:365:17)
   at require (module.js:384:17)
   at Object.<anonymous> (C:\Users\1\Documents\GitHub\Halcyon\node_modules\autoprefixer-core\lib\autoprefixer.js:6:13)
   at Object.<anonymous> (C:\Users\1\Documents\GitHub\Halcyon\node_modules\autoprefixer-core\lib\autoprefixer.js:113:4)
   at Module._compile (module.js:460:26)
   at Object.Module._extensions..js (module.js:478:10)
   at Module.load (module.js:355:32)
   at Function.Module._load (module.js:310:12) 
Помогите, пожалуйста.

**Comment by oozywaters** [comment]
Здравствуйте.

Да, такая ошибка почему-то возникает из-за animate-stylus. Пока не разбирался в причинах ее возникновения, но можно ее просто проигнорировать :)

Запустите 

``` bash
 $ bower i
```

затем

``` bash
 $ enb server
```

И все должно заработать

**Comment by VVE** [comment]
Здравствуйте! Сделал так (уточнение: не enb server, а так, как у Вас было написано), результат - тот же.
Error: Cannot find module 'postcss'
   at Function.Module._resolveFilename (module.js:336:15)
   at Function.Module._load (module.js:278:25)
   at Module.require (module.js:365:17)
   at require (module.js:384:17)
   at Object.<anonymous> (C:\Users\1\Documents\GitHub\Halcyon\node_modules\autoprefixer-core\lib\autoprefixer.js:6:13)
   at Object.<anonymous> (C:\Users\1\Documents\GitHub\Halcyon\node_modules\autoprefixer-core\lib\autoprefixer.js:113:4)
   at Module._compile (module.js:460:26)
   at Object.Module._extensions..js (module.js:478:10)
   at Module.load (module.js:355:32)
   at Function.Module._load (module.js:310:12)

**Comment by oozywaters** [comment]
К сожалению, сейчас нет возможности протестировать под Windows, поэтому буду давать устные рекомендации :)
Попробуйте заменить в файле package.json строчку

``` bash
"postinstall": "bower-npm-install"
```

на

``` bash
"postinstall": "bower install"
```

И произвести установку заново.
Если и это не поможет, то удалите строчку c animate-stylus из bower.json и установите пакет вручную в папку node_modules.

**Comment by VVE** [comment]
Здравствуйте! Замена строки в package.json не помогла.
А как установить пакет вручную?

**Comment by oozywaters** [comment]
В таком случае рекомендую установить рабочее окружение с linux-дистрибутивом, например отсюда: https://github.com/dab/bemup-workshop-vagrant

После этого необходимо зайти на виртуальную машину посредством любого SSH-клиента (я использовал PuTTY) и установить все необходимые пакеты (git, node.js, bem-cli и т.д.).

Особое внимание следует обратить на node.js. Для установки актуальной версии можно воспользоваться способом, описанным здесь: https://toster.ru/q/108311

После запуска enb server страницы будут доступны по адресу http://192.168.33.10:8080/desktop.bundles/index/index.html
